#!/usr/bin env node
const fs = require('fs');
const rootDir = `${__dirname}/..`;
require('shelljs/global');
const {BASE_DIR = `${rootDir}/pulse`, BUILD_DIR='/tmp/build', RESULT_DIR='/tmp/build_results'} = process.env;
mkdir('-p', RESULT_DIR);

const {GITHUB_OAUTH_TOKEN} = process.env;

if (!which('docker') || !which('java') || !which('curl') || !which('unzip')) {
  echo(`Failed to proceed without necessary application (git | docker | java | curl | unzip)`);
  exit(1);
}

require('./readInput')(json => {
  const {vcs_url, vcs_revision, build_num, subject} = json;
  const shortCommit = vcs_revision.substring(0, 5);
  const revisionDir = `${BUILD_DIR}/${build_num}`;
  rm('-rf', revisionDir);
  mkdir('-p', revisionDir);

  let downloadUrl = `${vcs_url}/archive/${vcs_revision}.zip`;

  const downloadReady = (!GITHUB_OAUTH_TOKEN)
    ? exec(`curl -# -L -o ${revisionDir}/${vcs_revision}.zip ${downloadUrl}`).code
    : exec(`curl -# -L -u ${GITHUB_OAUTH_TOKEN}:x-oauth-basic -o ${revisionDir}/${vcs_revision}.zip ${downloadUrl}`).code;

  if (downloadReady !== 0) {
    echo('Problem with downloading files');
    exit(1);
  }

  exec(`unzip ${revisionDir}/${vcs_revision}.zip -d ${revisionDir}`);

  exec(`${revisionDir}/pulse-${vcs_revision}/scripts/autoBuild ${effectiveBuildName} ${shortCommit} ${subject}`);
  exec(`rm -rf ${revisionDir}`);
});